django/blogs/urls.py
from django.urls import path

from . import views

app_name = 'blogs'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:blog_id>', views.details, name='details'),
    path('new/', views.new, name='new'),
    path('edit/<int:blog_id>', views.edit, name='edit'),
]

django/geeks_website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('events/', include('events.urls', namespace='events')),
    path('blogs/', include('blogs.urls', namespace='blogs')),
    path('account/', include('people.urls', namespace='people')),
]

django/home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('about_us', views.about_us, name='about_us'),
    path('weeklies', views.weeklies, name='weeklies'),
]

django/home/models.py
from django.db import models

# Create your models here.

django/home/views.py
from datetime import datetime

from django.shortcuts import render

from blogs.models import Blog
from events.models import Event


# Create your views here.
def index(request):
    context = {
        'events': Event.objects.filter(start_time__gt=datetime.now()
                                       ).order_by('-start_time')[:5],
        'blogs': Blog.objects.all().order_by('-last_edit_date')[:5],
    }

    return render(request, "home/index.html", context=context)


def about_us(request):
    return render(request, "home/about_us.html")


def weeklies(request):
    return render(request, "home/weeklies.html")

django/home/templates/home/about_us.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/home/about_us.css' %}">
{% endblock %}

{% block title %}About Us{% endblock %}

{% block body %}
<div style="max-width: 90%; margin: auto;">
    <p>
        McMaster Geeks is the largest general recreation and gaming community at McMaster. We run events and services for all interests that include but are not limited to <em><b>Gaming</b></em>, <em><b>Tabletop Games</b></em>, <em><b>Anime</b></em>, and beyond. These events can be weekly - such as our <em>Anime Nights</em>, <em>Trading Card Game Nights</em>, <em>Smash Weeklies</em>, <em>Dungeons & Dragons Oneshots</em>, and <em>Minecraft Nights</em>. We also will host larger events such as tournaments or social outings where members of our community can meet new friends for the hobbies that they enjoy the most. </p>
    <p>
        We also offer a Geeks membership card, which provides discounts and perks at our events along with our partners: <b>Board Game Central</b>, <b>Torchlight Games & Hobbies</b>, and <b>Black Knight Games</b>! No matter how you spend your free time, our club is dedicated to giving any and all McMaster students a welcoming space to enjoy the things they love.
    </p>
    <p>
        As we head into an online school semester, we are committed to nurturing our virtual space where students can participate in club events and build a community that spans out beyond Hamilton.
    </p>
    <p>
        Our Discord is where our online events are hosted, open for everyone to join, and a place to share anything geeky! Our Facebook and Instagram include important event information and announcements so you know when, where, and how exactly our events will be happening! Keep updated on our socials here:
    </p>

    <ul id="social">
        <li>
            <a href="https://discord.com/invite/zyytMtM"><img src="{% static 'img/logos/discord.svg' %}" alt="discord-logo"></a>
        </li>
        <li>
            <a href="https://www.instagram.com/mcmastergeeks/"><img src="{% static 'img/logos/instagram.svg' %}" alt="instagram-logo"></a>
        </li>
        <li>
            <a href="https://www.facebook.com/groups/McMasterGEEKS"><img src="{% static 'img/logos/facebook.svg' %}" alt="facebook-logo"></a>
        </li>
    </ul>

    <p>
        Also check out our <a href="https://www.facebook.com/McMasterGeeks">Facebook Events Page</a>.
    </p>
</div>
{% endblock %}

django/home/templates/home/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}McMaster Geeks Club{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/home/index.css' %}" >
{% endblock %}

{% block body %}

{% if events %}
<!-- events slide show -->
<div class="slideshow-container">
    {% for event in events %}

    <div class="mySlides fade">
        <div class="numbertext">{{ forloop.countr }}/{{ events|length }}</div>
        <a href="{% url 'events:details' event.id %}">
            <img src="{{ event.banner.url }}">
        </a>
        <div class="text"><h2>{{ event.title }}</h2></div>
    </div>

    {% endfor %}
    <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
    <a class="next" onclick="plusSlides(1)">&#10095;</a>
</div>
{% else %}
<div>
    <img id="weekly" src="{% static 'img/weekly_events.png' %}" alt="Weekly Events">
</div>
{% endif %}

<!-- News and blogs -->
<div class="blogs">
    <h3>News and Updates</h3>
    {% for blog in blogs %}
    {% if forloop.counter0 != 0 %}
    <hr>
    {% endif %}
        <div class="blog">
            <h2>{{ blog.title }}</h2>
            <em>
                <p>By: <b>{{ blog.author }}</b></p>
                <p>
                    Pub Date: {{ blog.pub_date }}
                    {% if blog.is_edited %}<br> Last Edit: {{ blog.last_edit_date }}{% endif %}
                </p>
            </em>
            <a href="{% url 'blogs:details' blog.id %}" class="blog"></a>
        </div>
    {% empty %}
    <h4>No updates</h4>
</div>
{% endfor %}

{% if events %}
<script src="{% static 'js/slide.js' %}"></script>
{% endif %}
{% endblock %}

django/home/templates/home/weeklies.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Weekly Events{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/home/index.css' %}" >
{% endblock %}

{% block body %}
<div>
    <img id="weekly" src="{% static 'img/weekly_events.png' %}" alt="Weekly Events" >
</div>
{% endblock %}