django/geeks_website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('events/', include('events.urls', namespace='events')),
    path('blogs/', include('blogs.urls', namespace='blogs')),
    path('account/', include('people.urls', namespace='people')),
]

django/home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('about_us', views.about_us, name='about_us'),
    path('weeklies', views.weeklies, name='weeklies'),
]

django/people/urls.py
from django.urls import path

from . import views

app_name = 'people'

urlpatterns = [
    path('', views.index, name='account'),
    path('login', views.login, name='login'),
    path('register', views.register, name='register'),
    path('logout', views.logout, name='logout'),
    path('password', views.change_pass, name='password'),
    path('membership', views.memberships, name='membership'),
    path('members', views.members, name='members'),
    path('card', views.card, name='card'),
    path('qrcode', views.QRcode, name='qrcode'),
]

django/home/models.py
from django.db import models

# Create your models here.

django/home/views.py
from datetime import datetime

from django.shortcuts import render

from blogs.models import Blog
from events.models import Event


# Create your views here.
def index(request):
    context = {
        'events': Event.objects.filter(start_time__gt=datetime.now()
                                       ).order_by('-start_time')[:5],
        'blogs': Blog.objects.all().order_by('-last_edit_date')[:5],
    }

    return render(request, "home/index.html", context=context)


def about_us(request):
    return render(request, "home/about_us.html")


def weeklies(request):
    return render(request, "home/weeklies.html")

django/home/templates/base.html
{% load static %}
<html lang="en">
    <head>
        <title>{% block title %}McMaster Geeks{% endblock %}</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <link rel="stylesheet" href="{% static 'css/base.css' %}" type="text/css" media="screen"/>
        <script src="{% static 'js/base.js' %}"></script>

        <script src="https://kit.fontawesome.com/423722d4ae.js" crossorigin="anonymous"></script>

        {% block head %}{% endblock %}
    </head>
    <body>
        <div id="body">
            <style>
             #header-img {
                 width: 100%;
                 min-height: 20vh;
                 max-height: 30vh;
                 background: url({% block head_img %}{% static 'img/header_default_geeks.jpg' %}{% endblock %}) 50% 50% no-repeat;
                 background-size: 100%;
                 overflow: hidden;
             }
            </style>
            <div id="header-img">
            </div>
            <div class="topnav" id="myTopnav">
                <a href="{% url 'home:index' %}">Home</a>
                <a href="{% url 'events:index' %}">Events</a>
                <a href="{% url 'home:weeklies' %}">Weekly Events</a>
                <a href="{% url 'blogs:index' %}">News</a>
                <!-- <div class="dropdown">
                     <button class="dropbtn">Dropdown
                     <i class="fa fa-caret-down"></i>
                     </button>
                     <div class="dropdown-content">
                     <a href="#">Link 1</a>
                     <a href="#">Link 2</a>
                     <a href="#">Link 3</a>
                     </div>
                     </div> -->
                <a href="{% url 'home:about_us' %}">About</a>
                {% if user.is_authenticated %}
                <a href="{% url 'people:account' %}">Account</a>
                {% else %}
                <a href="{% url 'people:login' %}">Login</a>
                <a href="{% url 'people:register' %}">Register</a>
                {% endif %}<a href="javascript:void(0);" class="icon" onclick="myFunction()">&#9776;</a>
            </div>
            {% block body %}
            {% endblock %}
            <script>
             function myFunction() {
                 var x = document.getElementById("myTopnav");
                 if (x.className === "topnav") {
                     x.className += " responsive";
                 } else {
                     x.className = "topnav";
                 }
             }
            </script>
        </div>
    </body>

</html>