django/geeks_website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('events/', include('events.urls', namespace='events')),
    path('blogs/', include('blogs.urls', namespace='blogs')),
    path('account/', include('people.urls', namespace='people')),
]

django/home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('about_us', views.about_us, name='about_us'),
    path('weeklies', views.weeklies, name='weeklies'),
]

django/people/urls.py
from django.urls import path

from . import views

app_name = 'people'

urlpatterns = [
    path('', views.index, name='account'),
    path('login', views.login, name='login'),
    path('register', views.register, name='register'),
    path('logout', views.logout, name='logout'),
    path('password', views.change_pass, name='password'),
    path('membership', views.memberships, name='membership'),
    path('members', views.members, name='members'),
    path('card', views.card, name='card'),
    path('qrcode', views.QRcode, name='qrcode'),
]

django/people/models.py
import uuid
from django import forms
from django.contrib.auth.models import User as U
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.translation import gettext_lazy as _


# Create your models here.
class Account(models.Model):
    user = models.OneToOneField(U,
                                on_delete=models.CASCADE,
                                primary_key=True)
    is_member = models.BooleanField(default=False)
    member_code = models.UUIDField(editable=True,
                                   blank=True,
                                   null=True)
    pending_member = models.BooleanField(default=False)

    class AccountTypes(models.TextChoices):
        MARKETING = 'MRKT', _('Marketing')
        EXEC = 'EXC', _('Exec')
        REGULAR = 'REG', _('Member')

    mem_type = models.CharField(max_length=4,
                                choices=AccountTypes.choices,
                                default=AccountTypes.REGULAR)

    @property
    def apply_for_membership(self):
        if (self.is_member):
            return False
        self.pending_member = True
        self.save()
        return True

    @property
    def make_member(self):
        if(self.is_member):
            return False
        self.pending_member = False
        self.is_member = True
        self.member_code = uuid.uuid4()
        self.save()
        return True

    class Meta:
        permissions = (
            ('make_member', 'Can give membership status'),
            ('see_members', "Can see a list of members"),
        )

    def __str__(self):
        return self.user.username


class RegisterForm(forms.Form):
    username = forms.CharField(max_length=50,
                               label="Username")
    f_name = forms.CharField(max_length=50,
                             label="First Name")
    l_name = forms.CharField(max_length=50,
                             label="Last Name")
    email = forms.EmailField(label="McMaster Email")
    password = forms.CharField(min_length=8,
                               widget=forms.PasswordInput,
                               label="Password")
    rep_password = forms.CharField(min_length=8,
                                   widget=forms.PasswordInput,
                                   label="Repeat Password")

    def clean_email(self):
        domain = self.cleaned_data['email'].split('@')[-1]
        if (domain.lower() != "mcmaster.ca"):
            raise ValidationError(
                "Invalid email. Please use your McMaster email.")
        if U.objects.filter(email=self.cleaned_data['email']).exists():
            raise ValidationError("Email exists")
        return self.cleaned_data['email']

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        rep_password = cleaned_data.get('rep_password')

        if rep_password != password:
            self.add_error('rep_password', ValidationError(
                "Passwords do not match."))


class LoginForm(forms.Form):
    username = forms.CharField(max_length=50,
                               label='Username')
    password = forms.CharField(min_length=8,
                               widget=forms.PasswordInput,
                               label='Password')

django/people/views.py
import uuid
from datetime import date
from io import BytesIO
from tempfile import NamedTemporaryFile, TemporaryFile

import qrcode
from django.contrib import messages
from django.contrib.auth import authenticate
from django.contrib.auth import login as l_in
from django.contrib.auth import logout as l_out
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.models import User as U
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from fpdf import FPDF

from .models import Account, LoginForm, RegisterForm


# Create your views here.
def index(request):
    if (not request.user.is_authenticated):
        return redirect('people:login')
    context = {'member': request.user.account}
    return render(request, 'people/index.html', context=context)


def login(request):
    if (request.user.is_authenticated):
        return redirect('people:account')
    if (request.method == 'POST'):
        form = LoginForm(request.POST)
        if (form.is_valid()):
            data = form.cleaned_data
            username = data.get('username')
            password = data.get('password')
            user = authenticate(username=username, password=password)
            if user:
                if user.is_active:
                    l_in(request, user)
                    return redirect('people:account')
                else:
                    form.add_error('username',
                                   "Account is inactive."
                                   " Contact Admin for activation.")
            else:
                form.add_error('password', "Wrong Username or Password")
    else:
        form = LoginForm()
    return render(request, 'misc/forms.html', {'form': form,
                                               'target': 'people:login',
                                               'submit': 'Login',
                                               'title': 'Login'})


def logout(request):
    if (request.user.is_authenticated):
        l_out(request)
    return redirect('home:index')


def register(request):

    if (request.user.is_authenticated):
        return redirect('people:account')

    if (request.method == 'POST'):
        form = RegisterForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user = U.objects.create_user(
                username=data.get('username'),
                first_name=data.get('f_name'),
                last_name=data.get('l_name'),
                email=data.get('email'),
                password=data.get('password'),
                is_staff=False,
                is_superuser=False,
                is_active=True,)

            user.save()

            is_member: bool
            mem_uuid: uuid
            if date.today() < date(year=2020, month=10, day=1):
                is_member = True
                mem_uuid = uuid.uuid4()

                account = Account(user=user,
                                  is_member=is_member,
                                  member_code=mem_uuid)
            else:
                account = Account(user=user)

            account.save()
            l_in(request, user)
            return redirect('people:register')

    else:
        form = RegisterForm()

    return render(request, 'misc/forms.html', {'form': form,
                                               'target': 'people:register',
                                               'submit': 'Register',
                                               'title': 'Register'})


@permission_required('people.make_member', raise_exception=True)
def memberships(request):
    if ('member' in request.GET):
        acc = get_object_or_404(Account, pk=request.GET['member'])
        if (acc.make_member):
            return HttpResponse('Given membership successfully.')
        else:
            return HttpResponse('Failed to give membership.'
                                ' Please contact admin.')
    else:
        context = {'members':
                   Account.objects.filter(pending_member__exact=True)}
        return render(request, 'people/memberships.html', context=context)


@permission_required('people.see_members', raise_exception=True)
def members(request):
    if (request.POST):
        f_name = request.POST['f_name']
        l_name = request.POST['l_name']
        members = Account.objects.filter(
            user__first_name__icontains=f_name,
            user__last_name__icontains=l_name)
        if 'is_member' in request.POST:
            members = members.filter(is_member=True)
        context = {"members": members.order_by('user__first_name',
                                               'user__last_name')}
    else:
        context = {"members": Account.objects.all().order_by(
            'user__first_name',
            'user__last_name')}
    return render(request, 'people/members.html', context=context)


def change_pass(request):
    if (not request.user.is_authenticated):
        return redirect('people:login')

    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request,
                             'Your password was successfully updated!')
            return redirect('change_password')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'misc/forms.html', {
        'form': form,
        'target': "people:password",
        'submit': "Change Password",
        'title': "Change Password"
    })


def card(request):
    if (not request.user.is_authenticated):
        return redirect('people:login')
    account = request.user.account
    pdf = FPDF('L', 'mm', (51, 89))

    pdf.add_page()
    pdf.image('/usr/static/img/people/front.png', x=0, y=0, w=89, h=51,
              type='PNG')

    # backside
    pdf.add_page()
    pdf.image('/usr/static/img/people/back.png', x=0, y=0, w=89, h=51,
              type='PNG')

    # first name
    pdf.set_font('arial', size=14.2)
    pdf.text(x=14, y=20.5, txt=account.user.first_name)

    # last name
    pdf.set_font('arial', size=14.2)
    pdf.text(x=14, y=29, txt=account.user.last_name)

    # code
    pdf.set_font('arial', size=6)
    if (account.is_member):
        pdf.text(x=14, y=42.5, txt=account.member_code.urn[9:])
    else:
        pdf.text(x=14, y=42.5, txt='c61cb43a-00ed-4f8b-bb2c-4cb4438822ec')

    if (request.user.account.is_member):
        img = qrcode.make(account.member_code)
    else:
        img = qrcode.make('https://www.youtube.com/watch?v=dQw4w9WgXcQ')
    imgBytes = BytesIO()
    img.save(imgBytes)
    with NamedTemporaryFile() as qr:

        qr.write(imgBytes.getvalue())
        # qr code
        qr.seek(0)
        pdf.image(qr.name, x=60, y=18, w=27, type='PNG')

        b = bytes(pdf.output(dest='S'), 'latin')
        with TemporaryFile() as card:
            card.write(b)
            card.seek(0)
            return HttpResponse(card, content_type='application/pdf')


def QRcode(request):
    if (not request.user.is_authenticated):
        return redirect('people:login')
    if (request.user.account.is_member):
        img = qrcode.make(request.user.account.member_code)
    else:
        img = qrcode.make('https://www.youtube.com/watch?v=dQw4w9WgXcQ')
    imgBytes = BytesIO()
    img.save(imgBytes)
    with TemporaryFile() as qr:

        qr.write(imgBytes.getvalue())
        qr.seek(0)
        return HttpResponse(qr, content_type='image/png')

django/people/templates/people/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ member.user.first_name }}'sProfile{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/people/index.css' %}">
{% endblock %}

{% block body %}
<div class="container">
    <div class="main-section">

        {% if not member.is_member %}
        <a class="button" href="#">Request Membership, 10CAD(WIP)</a>
        <br>
        {% endif %}

        {% if user.is_staff %}
        <a class="button" href="/admin/">Admin page</a>
        <br>
        {% endif %}

        {% if perms.people.make_member %}
        <a class="button" href="{% url 'people:membership' %}">See membership applications</a>
        <br>
        {% endif %}

        {% if perms.people.see_member %}
        <a class="button" href="{% url 'people:members' %}">See members</a>
        <br>
        {% endif %}

        <br>
        <a class="button" href="{% url 'people:password' %}">Change Password</a>

        <br>
        <a class="button" href="{% url 'people:logout' %}">Logout</a>
    </div>
    <div class="main-section">
        <h2>{{ member.user.first_name }} {{ member.user.last_name }}</h2>

        <h3><b>Email:</b> {{ member.user.email }}</h3>

        {% if user.is_staff %}
        <h3>
            <b>Account Groups:</b> {% for group in user.groups.all %} <p style="margin-left: 2em">{{ group.name }}</p> {% endfor %}
        </h3>
        {% endif %}

        {% if member.is_member %}
        <h3>
            <b>Membership Code:</b>
        </h3>
        <img style="width:50%" src="{% url 'people:qrcode' %}" alt="qrcode">
        {% endif %}

    </div>
</div>
{% endblock %}

django/people/templates/people/members.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Members{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/people/members.css' %}" >
{% endblock %}

{% block body %}
<form method="post", action="{% url 'people:members' %}">
    {% csrf_token %}
    <table>
        <tr>
            <td>
                <label for="f_name">First Name:</label>
            </td>
            <td>
                <input name="f_name" type="text">
            </td>
        </tr>
        <tr>
            <td>
                <label for="l_name">Last Name:</label>
            </td>
            <td>
                <input name="l_name" type="text">
            </td>
        </tr>
        <tr>
            <td>
                <label for="is_member">Paid Members:</label>
            </td>
            <td>
                <input type="checkbox" id="is_member" name="is_member" value="yes">
            </td>
        </tr>
    </table>
    <input type="submit" value="Submit"/>
</form>
<br>
<table class="members">
    <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
    </tr>
    {% for member in members %}
    <tr>
        <td>{{ member.user.first_name }}</td>
        <td>{{ member.user.last_name }}</td>
        <td>{{ member.user.email }}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

django/people/templates/people/memberships.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Membership Management{% endblock %}


{% block body %}
{% if members %}
<table>
{% for member in members %}
    <tr>
        <td>{{ member.user.username }}</td>
        <td>{{ member.user.email }}</td>
        <td>
            <form action="{% url 'people:membership' %}" method="GET">
                <!-- <input name="member" value="{{ member.id }}" > -->
                <input type="submit" name="member" value="{{ member.pk }}">
            </form>
        </td>
    </tr>
{% endfor%}
</table>
{% else %}

<h3>No membership requests!</h3>

{% endif %}
{% endblock body %}